package imqdb;

import java.util.ArrayList;

public class QueryFactory {

	public final static Query dummy = new Query(
		"~~ Select a query! ~~", "qc/q_dummy.fxml"
	);

	public static ArrayList<Query> generate()
	{
		ArrayList<Query> queries = new ArrayList<Query>();

		queries.add(
			new Query("Table Browser", "qc/q_all_tables.fxml")
		);

		queries.add(
			new Query("Highest Gross Income by Year", "qc/q_gross_by_year.fxml")
		);

		queries.add(
			new Query("Billion Dollar Club", "qc/q_billion_club.fxml")
		);

		queries.add(
			new Query("Movie Rating", "qc/q_movie_rating.fxml")
		);

		queries.add(
				new Query("Movie Duration", "qc/q_movie_duration.fxml")
		);

		queries.add(
			new Query("Family Fun", "qc/q_family_fun.fxml")
		);

		queries.add(
			new Query("Money Generated by Artist + Family", "qc/q_artist_money_generated.fxml")
		);

		queries.add(
				new Query("Most or Least Watched Movies", "qc/q_most_least_watched.fxml")
		);

		queries.add(
			new Query("Frequent Collaborators", "qc/q_frequent_collaborators.fxml")
		);

		queries.add(
				new Query("Matchmaker Movies", "qc/q_matchmaker.fxml")
		);

		return queries;
	}

}
